// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: taskbounty/v1/query.proto

package types

import (
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksRequest) Reset() {
	*x = QueryTasksRequest{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksRequest) ProtoMessage() {}

func (x *QueryTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksRequest.ProtoReflect.Descriptor instead.
func (*QueryTasksRequest) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryTasksRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksResponse) Reset() {
	*x = QueryTasksResponse{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksResponse) ProtoMessage() {}

func (x *QueryTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksResponse.ProtoReflect.Descriptor instead.
func (*QueryTasksResponse) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *QueryTasksResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTaskRequest) Reset() {
	*x = QueryTaskRequest{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTaskRequest) ProtoMessage() {}

func (x *QueryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTaskRequest.ProtoReflect.Descriptor instead.
func (*QueryTaskRequest) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTaskResponse) Reset() {
	*x = QueryTaskResponse{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTaskResponse) ProtoMessage() {}

func (x *QueryTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTaskResponse.ProtoReflect.Descriptor instead.
func (*QueryTaskResponse) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type QueryTasksByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=taskbounty.v1.TaskStatus" json:"status,omitempty"`
	Pagination    *query.PageRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksByStatusRequest) Reset() {
	*x = QueryTasksByStatusRequest{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksByStatusRequest) ProtoMessage() {}

func (x *QueryTasksByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksByStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryTasksByStatusRequest) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryTasksByStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *QueryTasksByStatusRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTasksByStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksByStatusResponse) Reset() {
	*x = QueryTasksByStatusResponse{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksByStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksByStatusResponse) ProtoMessage() {}

func (x *QueryTasksByStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksByStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryTasksByStatusResponse) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryTasksByStatusResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *QueryTasksByStatusResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTasksByCreatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Pagination    *query.PageRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksByCreatorRequest) Reset() {
	*x = QueryTasksByCreatorRequest{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksByCreatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksByCreatorRequest) ProtoMessage() {}

func (x *QueryTasksByCreatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksByCreatorRequest.ProtoReflect.Descriptor instead.
func (*QueryTasksByCreatorRequest) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryTasksByCreatorRequest) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *QueryTasksByCreatorRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTasksByCreatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksByCreatorResponse) Reset() {
	*x = QueryTasksByCreatorResponse{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksByCreatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksByCreatorResponse) ProtoMessage() {}

func (x *QueryTasksByCreatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksByCreatorResponse.ProtoReflect.Descriptor instead.
func (*QueryTasksByCreatorResponse) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryTasksByCreatorResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *QueryTasksByCreatorResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTasksByClaimantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claimant      string                 `protobuf:"bytes,1,opt,name=claimant,proto3" json:"claimant,omitempty"`
	Pagination    *query.PageRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksByClaimantRequest) Reset() {
	*x = QueryTasksByClaimantRequest{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksByClaimantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksByClaimantRequest) ProtoMessage() {}

func (x *QueryTasksByClaimantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksByClaimantRequest.ProtoReflect.Descriptor instead.
func (*QueryTasksByClaimantRequest) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryTasksByClaimantRequest) GetClaimant() string {
	if x != nil {
		return x.Claimant
	}
	return ""
}

func (x *QueryTasksByClaimantRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTasksByClaimantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksByClaimantResponse) Reset() {
	*x = QueryTasksByClaimantResponse{}
	mi := &file_taskbounty_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksByClaimantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksByClaimantResponse) ProtoMessage() {}

func (x *QueryTasksByClaimantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksByClaimantResponse.ProtoReflect.Descriptor instead.
func (*QueryTasksByClaimantResponse) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryTasksByClaimantResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *QueryTasksByClaimantResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_taskbounty_v1_query_proto protoreflect.FileDescriptor

const file_taskbounty_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x19taskbounty/v1/query.proto\x12\rtaskbounty.v1\x1a\x14gogoproto/gogo.proto\x1a\x18taskbounty/v1/task.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1cgoogle/api/annotations.proto\"[\n" +
	"\x11QueryTasksRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x8e\x01\n" +
	"\x12QueryTasksResponse\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.taskbounty.v1.TaskB\x04\xc8\xde\x1f\x00R\x05tasks\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"\"\n" +
	"\x10QueryTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x11QueryTaskResponse\x12-\n" +
	"\x04task\x18\x01 \x01(\v2\x13.taskbounty.v1.TaskB\x04\xc8\xde\x1f\x00R\x04task\"\x96\x01\n" +
	"\x19QueryTasksByStatusRequest\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.taskbounty.v1.TaskStatusR\x06status\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x96\x01\n" +
	"\x1aQueryTasksByStatusResponse\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.taskbounty.v1.TaskB\x04\xc8\xde\x1f\x00R\x05tasks\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"~\n" +
	"\x1aQueryTasksByCreatorRequest\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x97\x01\n" +
	"\x1bQueryTasksByCreatorResponse\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.taskbounty.v1.TaskB\x04\xc8\xde\x1f\x00R\x05tasks\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"\x81\x01\n" +
	"\x1bQueryTasksByClaimantRequest\x12\x1a\n" +
	"\bclaimant\x18\x01 \x01(\tR\bclaimant\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x98\x01\n" +
	"\x1cQueryTasksByClaimantResponse\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.taskbounty.v1.TaskB\x04\xc8\xde\x1f\x00R\x05tasks\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination2\xd7\x05\n" +
	"\x05Query\x12r\n" +
	"\x05Tasks\x12 .taskbounty.v1.QueryTasksRequest\x1a!.taskbounty.v1.QueryTasksResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/dao-golang/taskbounty/tasks\x12t\n" +
	"\x04Task\x12\x1f.taskbounty.v1.QueryTaskRequest\x1a .taskbounty.v1.QueryTaskResponse\")\x82\xd3\xe4\x93\x02#\x12!/dao-golang/taskbounty/tasks/{id}\x12\x9a\x01\n" +
	"\rTasksByStatus\x12(.taskbounty.v1.QueryTasksByStatusRequest\x1a).taskbounty.v1.QueryTasksByStatusResponse\"4\x82\xd3\xe4\x93\x02.\x12,/dao-golang/taskbounty/tasks/status/{status}\x12\x9f\x01\n" +
	"\x0eTasksByCreator\x12).taskbounty.v1.QueryTasksByCreatorRequest\x1a*.taskbounty.v1.QueryTasksByCreatorResponse\"6\x82\xd3\xe4\x93\x020\x12./dao-golang/taskbounty/tasks/creator/{creator}\x12\xa4\x01\n" +
	"\x0fTasksByClaimant\x12*.taskbounty.v1.QueryTasksByClaimantRequest\x1a+.taskbounty.v1.QueryTasksByClaimantResponse\"8\x82\xd3\xe4\x93\x022\x120/dao-golang/taskbounty/tasks/claimant/{claimant}B2Z0github.com/nutcase/dao-golang/x/taskbounty/typesb\x06proto3"

var (
	file_taskbounty_v1_query_proto_rawDescOnce sync.Once
	file_taskbounty_v1_query_proto_rawDescData []byte
)

func file_taskbounty_v1_query_proto_rawDescGZIP() []byte {
	file_taskbounty_v1_query_proto_rawDescOnce.Do(func() {
		file_taskbounty_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskbounty_v1_query_proto_rawDesc), len(file_taskbounty_v1_query_proto_rawDesc)))
	})
	return file_taskbounty_v1_query_proto_rawDescData
}

var file_taskbounty_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_taskbounty_v1_query_proto_goTypes = []any{
	(*QueryTasksRequest)(nil),            // 0: taskbounty.v1.QueryTasksRequest
	(*QueryTasksResponse)(nil),           // 1: taskbounty.v1.QueryTasksResponse
	(*QueryTaskRequest)(nil),             // 2: taskbounty.v1.QueryTaskRequest
	(*QueryTaskResponse)(nil),            // 3: taskbounty.v1.QueryTaskResponse
	(*QueryTasksByStatusRequest)(nil),    // 4: taskbounty.v1.QueryTasksByStatusRequest
	(*QueryTasksByStatusResponse)(nil),   // 5: taskbounty.v1.QueryTasksByStatusResponse
	(*QueryTasksByCreatorRequest)(nil),   // 6: taskbounty.v1.QueryTasksByCreatorRequest
	(*QueryTasksByCreatorResponse)(nil),  // 7: taskbounty.v1.QueryTasksByCreatorResponse
	(*QueryTasksByClaimantRequest)(nil),  // 8: taskbounty.v1.QueryTasksByClaimantRequest
	(*QueryTasksByClaimantResponse)(nil), // 9: taskbounty.v1.QueryTasksByClaimantResponse
	(*query.PageRequest)(nil),            // 10: cosmos.base.query.v1beta1.PageRequest
	(*Task)(nil),                         // 11: taskbounty.v1.Task
	(*query.PageResponse)(nil),           // 12: cosmos.base.query.v1beta1.PageResponse
	(TaskStatus)(0),                      // 13: taskbounty.v1.TaskStatus
}
var file_taskbounty_v1_query_proto_depIdxs = []int32{
	10, // 0: taskbounty.v1.QueryTasksRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	11, // 1: taskbounty.v1.QueryTasksResponse.tasks:type_name -> taskbounty.v1.Task
	12, // 2: taskbounty.v1.QueryTasksResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	11, // 3: taskbounty.v1.QueryTaskResponse.task:type_name -> taskbounty.v1.Task
	13, // 4: taskbounty.v1.QueryTasksByStatusRequest.status:type_name -> taskbounty.v1.TaskStatus
	10, // 5: taskbounty.v1.QueryTasksByStatusRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	11, // 6: taskbounty.v1.QueryTasksByStatusResponse.tasks:type_name -> taskbounty.v1.Task
	12, // 7: taskbounty.v1.QueryTasksByStatusResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	10, // 8: taskbounty.v1.QueryTasksByCreatorRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	11, // 9: taskbounty.v1.QueryTasksByCreatorResponse.tasks:type_name -> taskbounty.v1.Task
	12, // 10: taskbounty.v1.QueryTasksByCreatorResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	10, // 11: taskbounty.v1.QueryTasksByClaimantRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	11, // 12: taskbounty.v1.QueryTasksByClaimantResponse.tasks:type_name -> taskbounty.v1.Task
	12, // 13: taskbounty.v1.QueryTasksByClaimantResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	0,  // 14: taskbounty.v1.Query.Tasks:input_type -> taskbounty.v1.QueryTasksRequest
	2,  // 15: taskbounty.v1.Query.Task:input_type -> taskbounty.v1.QueryTaskRequest
	4,  // 16: taskbounty.v1.Query.TasksByStatus:input_type -> taskbounty.v1.QueryTasksByStatusRequest
	6,  // 17: taskbounty.v1.Query.TasksByCreator:input_type -> taskbounty.v1.QueryTasksByCreatorRequest
	8,  // 18: taskbounty.v1.Query.TasksByClaimant:input_type -> taskbounty.v1.QueryTasksByClaimantRequest
	1,  // 19: taskbounty.v1.Query.Tasks:output_type -> taskbounty.v1.QueryTasksResponse
	3,  // 20: taskbounty.v1.Query.Task:output_type -> taskbounty.v1.QueryTaskResponse
	5,  // 21: taskbounty.v1.Query.TasksByStatus:output_type -> taskbounty.v1.QueryTasksByStatusResponse
	7,  // 22: taskbounty.v1.Query.TasksByCreator:output_type -> taskbounty.v1.QueryTasksByCreatorResponse
	9,  // 23: taskbounty.v1.Query.TasksByClaimant:output_type -> taskbounty.v1.QueryTasksByClaimantResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_taskbounty_v1_query_proto_init() }
func file_taskbounty_v1_query_proto_init() {
	if File_taskbounty_v1_query_proto != nil {
		return
	}
	file_taskbounty_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskbounty_v1_query_proto_rawDesc), len(file_taskbounty_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskbounty_v1_query_proto_goTypes,
		DependencyIndexes: file_taskbounty_v1_query_proto_depIdxs,
		MessageInfos:      file_taskbounty_v1_query_proto_msgTypes,
	}.Build()
	File_taskbounty_v1_query_proto = out.File
	file_taskbounty_v1_query_proto_goTypes = nil
	file_taskbounty_v1_query_proto_depIdxs = nil
}
