// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: taskbounty/v1/task.proto

package types

import (
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus represents the current state of a task
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED     TaskStatus = 0
	TaskStatus_TASK_STATUS_OPEN            TaskStatus = 1
	TaskStatus_TASK_STATUS_CLAIMED         TaskStatus = 2
	TaskStatus_TASK_STATUS_PROOF_SUBMITTED TaskStatus = 3
	TaskStatus_TASK_STATUS_COMPLETED       TaskStatus = 4
	TaskStatus_TASK_STATUS_CANCELLED       TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_OPEN",
		2: "TASK_STATUS_CLAIMED",
		3: "TASK_STATUS_PROOF_SUBMITTED",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":     0,
		"TASK_STATUS_OPEN":            1,
		"TASK_STATUS_CLAIMED":         2,
		"TASK_STATUS_PROOF_SUBMITTED": 3,
		"TASK_STATUS_COMPLETED":       4,
		"TASK_STATUS_CANCELLED":       5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_taskbounty_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_taskbounty_v1_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_taskbounty_v1_task_proto_rawDescGZIP(), []int{0}
}

// Task represents a bounty task in the system
type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator        string                 `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"` // address of the task creator
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Bounty         *types.Coin            `protobuf:"bytes,5,opt,name=bounty,proto3" json:"bounty,omitempty"` // token amount and denom
	Status         TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=taskbounty.v1.TaskStatus" json:"status,omitempty"`
	Claimant       string                 `protobuf:"bytes,7,opt,name=claimant,proto3" json:"claimant,omitempty"` // address of the user who claimed the task
	ProofOfWorkUri string                 `protobuf:"bytes,8,opt,name=proof_of_work_uri,json=proofOfWorkUri,proto3" json:"proof_of_work_uri,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ChainId        string                 `protobuf:"bytes,11,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"` // Know Freedom chain ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_taskbounty_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_taskbounty_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_taskbounty_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetBounty() *types.Coin {
	if x != nil {
		return x.Bounty
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetClaimant() string {
	if x != nil {
		return x.Claimant
	}
	return ""
}

func (x *Task) GetProofOfWorkUri() string {
	if x != nil {
		return x.ProofOfWorkUri
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

var File_taskbounty_v1_task_proto protoreflect.FileDescriptor

const file_taskbounty_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x18taskbounty/v1/task.proto\x12\rtaskbounty.v1\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ecosmos/base/v1beta1/coin.proto\"\xd9\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\acreator\x18\x02 \x01(\tB\x12\xf2\xde\x1f\x0eyaml:\"creator\"R\acreator\x12&\n" +
	"\x05title\x18\x03 \x01(\tB\x10\xf2\xde\x1f\fyaml:\"title\"R\x05title\x128\n" +
	"\vdescription\x18\x04 \x01(\tB\x16\xf2\xde\x1f\x12yaml:\"description\"R\vdescription\x127\n" +
	"\x06bounty\x18\x05 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x06bounty\x12D\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.taskbounty.v1.TaskStatusB\x11\xf2\xde\x1f\ryaml:\"status\"R\x06status\x12/\n" +
	"\bclaimant\x18\a \x01(\tB\x13\xf2\xde\x1f\x0fyaml:\"claimant\"R\bclaimant\x12G\n" +
	"\x11proof_of_work_uri\x18\b \x01(\tB\x1c\xf2\xde\x1f\x18yaml:\"proof_of_work_uri\"R\x0eproofOfWorkUri\x12C\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\tcreatedAt\x12C\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\tupdatedAt\x12.\n" +
	"\bchain_id\x18\v \x01(\tB\x13\xf2\xde\x1f\x0fyaml:\"chain_id\"R\achainId*\xaf\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TASK_STATUS_OPEN\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_CLAIMED\x10\x02\x12\x1f\n" +
	"\x1bTASK_STATUS_PROOF_SUBMITTED\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x05B2Z0github.com/nutcase/dao-golang/x/taskbounty/typesb\x06proto3"

var (
	file_taskbounty_v1_task_proto_rawDescOnce sync.Once
	file_taskbounty_v1_task_proto_rawDescData []byte
)

func file_taskbounty_v1_task_proto_rawDescGZIP() []byte {
	file_taskbounty_v1_task_proto_rawDescOnce.Do(func() {
		file_taskbounty_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskbounty_v1_task_proto_rawDesc), len(file_taskbounty_v1_task_proto_rawDesc)))
	})
	return file_taskbounty_v1_task_proto_rawDescData
}

var file_taskbounty_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_taskbounty_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_taskbounty_v1_task_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: taskbounty.v1.TaskStatus
	(*Task)(nil),                  // 1: taskbounty.v1.Task
	(*types.Coin)(nil),            // 2: cosmos.base.v1beta1.Coin
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_taskbounty_v1_task_proto_depIdxs = []int32{
	2, // 0: taskbounty.v1.Task.bounty:type_name -> cosmos.base.v1beta1.Coin
	0, // 1: taskbounty.v1.Task.status:type_name -> taskbounty.v1.TaskStatus
	3, // 2: taskbounty.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: taskbounty.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_taskbounty_v1_task_proto_init() }
func file_taskbounty_v1_task_proto_init() {
	if File_taskbounty_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskbounty_v1_task_proto_rawDesc), len(file_taskbounty_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskbounty_v1_task_proto_goTypes,
		DependencyIndexes: file_taskbounty_v1_task_proto_depIdxs,
		EnumInfos:         file_taskbounty_v1_task_proto_enumTypes,
		MessageInfos:      file_taskbounty_v1_task_proto_msgTypes,
	}.Build()
	File_taskbounty_v1_task_proto = out.File
	file_taskbounty_v1_task_proto_goTypes = nil
	file_taskbounty_v1_task_proto_depIdxs = nil
}
